  version: "3.8"
  services:
    database:
      container_name: postgres_container
      image: postgres:latest
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: TestTask
      ports:
        - "5432:5432"
    pgadmin:
      container_name: pgadmin4_container
      image: dpage/pgadmin4:latest
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: root
      ports:
        - "5050:80"
    spring_application:
      container_name: spring_application
      build: .
      ports:
        - "8080:8080"
      depends_on:
        - database